# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='element_collection_ephemere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('confirm', models.BooleanField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='collection_ephemere/')),
                ('text_description_short', models.CharField(max_length=200)),
                ('text_description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=20)),
                ('taille', models.CharField(choices=[('lg', 'large'), ('md', 'medium'), ('sm', 'small'), ('xs', 'very small')], default='md', max_length=2)),
                ('nombre_colonnes', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='12', max_length=2)),
                ('nombre_offset', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='0', max_length=2)),
                ('couleur_text', models.CharField(default='#111111', max_length=7)),
                ('couleur_fond', models.CharField(default='#FFFFFF', max_length=7)),
                ('couleur_fond_image', models.CharField(default='#FFFFFF', max_length=7)),
                ('contour_arrondi', models.PositiveSmallIntegerField(default=0)),
                ('contour_arrondi_image', models.PositiveSmallIntegerField(default=0)),
                ('type_contour', models.CharField(choices=[('dotted', 'dotted'), ('dashed', 'dashed'), ('solid', 'solid'), ('double', 'double'), ('groove', 'groove'), ('ridge', 'ridge'), ('inset', 'inset'), ('outset', 'outset'), ('none', 'none'), ('hidden', 'hidden')], default='none', max_length=15)),
                ('couleur_contour', models.CharField(max_length=7)),
                ('epaisseur_contour', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
