# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='element_collection_ephemere',
            new_name='Produit',
        ),
    ]
