# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-23 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0002_auto_20161019_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='produit/'),
        ),
    ]
