# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0004_achat_produit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='achat_produit',
            new_name='achatProduit',
        ),
    ]
