# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0006_ongletachetez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongletachetez',
            name='image_titre',
            field=models.ImageField(upload_to='achetez/titre/'),
        ),
    ]
