# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0007_auto_20161104_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='achatCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('titre', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='achetez/categorie/')),
                ('taille', models.CharField(choices=[('lg', 'large'), ('md', 'medium'), ('sm', 'small'), ('xs', 'very small')], default='md', max_length=2)),
                ('nombre_colonnes', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='12', max_length=2)),
                ('nombre_offset', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='0', max_length=2)),
                ('couleur_titre', models.CharField(default='white', max_length=7)),
                ('confirm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ligneCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField()),
                ('categorie_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_1', to='achetez.achatCategorie')),
                ('categorie_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_2', to='achetez.achatCategorie')),
            ],
        ),
        migrations.DeleteModel(
            name='achatProduit',
        ),
    ]
