# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0008_auto_20161104_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecategorie',
            name='categorie_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_3', to='achetez.achatCategorie'),
            preserve_default=False,
        ),
    ]
