# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0009_lignecategorie_categorie_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatcategorie',
            name='nombre_colonnes',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='3', max_length=2),
        ),
        migrations.AlterField(
            model_name='achatcategorie',
            name='taille',
            field=models.CharField(choices=[('lg', 'large'), ('md', 'medium'), ('sm', 'small'), ('xs', 'very small')], default='xs', max_length=2),
        ),
    ]
