# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0011_auto_20161104_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecategorie',
            name='categorie_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_2', to='achetez.achatCategorie'),
        ),
        migrations.AlterField(
            model_name='lignecategorie',
            name='categorie_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_3', to='achetez.achatCategorie'),
        ),
    ]
