# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0012_auto_20161104_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecategorie',
            name='nom',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
