# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0013_lignecategorie_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='achatLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('logo', models.ImageField(upload_to='achetez/logo/')),
                ('date', models.DateField()),
                ('text_description_short', models.CharField(max_length=140)),
                ('couleur_text', models.CharField(default='black', max_length=7)),
                ('taille', models.CharField(choices=[('lg', 'large'), ('md', 'medium'), ('sm', 'small'), ('xs', 'very small')], default='md', max_length=2)),
                ('nombre_colonnes', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='3', max_length=2)),
                ('nombre_offset', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='0', max_length=2)),
                ('couleur_titre', models.CharField(default='white', max_length=7)),
                ('confirm', models.BooleanField()),
            ],
        ),
    ]
