# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0015_achatcategorie_logos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achatcategorie',
            name='logos',
        ),
    ]
