# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0017_achatcategorie_logos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achatcategorie',
            name='logos',
        ),
        migrations.AddField(
            model_name='achatlogo',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='achetez.achatCategorie'),
            preserve_default=False,
        ),
    ]
