# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0018_auto_20161107_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecategorie',
            options={'verbose_name': "Ligne de cat\xe9gorie de l'onglet Achetez "},
        ),
    ]
