# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0019_auto_20161107_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achatcategorie',
            options={'verbose_name': "Cat\xe9gorie de l'onglet Achetez", 'verbose_name_plural': "Cat\xe9gories de l'onglet Achetez"},
        ),
        migrations.AlterModelOptions(
            name='lignecategorie',
            options={'verbose_name': "Ligne de cat\xe9gorie de l'onglet Achetez ", 'verbose_name_plural': "Ligne de cat\xe9gorie de l'onglet Achetez "},
        ),
        migrations.AlterModelOptions(
            name='ongletachetez',
            options={'verbose_name': "Pr\xe9sentation de l'onglet Achetez", 'verbose_name_plural': "Pr\xe9sentation de l'onglet Achetez"},
        ),
    ]
