# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0020_auto_20161107_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achatlogo',
            options={'verbose_name': "logo de l'onglet Achetez", 'verbose_name_plural': "logos de l'onglet Achetez"},
        ),
    ]
