# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0021_auto_20161107_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongletachetez',
            name='image_titre',
            field=models.ImageField(upload_to='image_titre'),
        ),
    ]
