# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-04 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutsomise', '0009_customiseonglet_description'),
        ('achetez', '0024_ongletachetez_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cutsomise.customiseCategorie'),
            preserve_default=False,
        ),
    ]
