# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-07 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0025_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='couleur_contour',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='achetez/produit/'),
        ),
    ]
