# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-01 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0028_auto_20170507_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecategorie',
            name='categorie_1',
        ),
        migrations.RemoveField(
            model_name='lignecategorie',
            name='categorie_2',
        ),
        migrations.RemoveField(
            model_name='lignecategorie',
            name='categorie_3',
        ),
        migrations.DeleteModel(
            name='ligneCategorie',
        ),
    ]
