# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0029_auto_20170701_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dosStyle',
            field=models.ImageField(default=1, upload_to='achetez/produit/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='droiteStyle',
            field=models.ImageField(default=1, upload_to='achetez/produit/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='faceStyle',
            field=models.ImageField(default=1, upload_to='achetez/produit/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='gaucheStyle',
            field=models.ImageField(default=1, upload_to='achetez/produit/'),
            preserve_default=False,
        ),
    ]
