# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0030_auto_20170722_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dos',
            field=models.ImageField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dosStyle',
            field=models.ImageField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='droite',
            field=models.ImageField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='droiteStyle',
            field=models.ImageField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='face',
            field=models.ImageField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='faceStyle',
            field=models.ImageField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='gauche',
            field=models.ImageField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='gaucheStyle',
            field=models.ImageField(blank=True, upload_to='achetez/produit/'),
        ),
    ]
