# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-22 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0031_auto_20170722_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': "produits de l'onglet Achetez", 'verbose_name_plural': "produits de l'onglet Achetez"},
        ),
    ]
