# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-22 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0032_auto_20170722_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='dosStyle',
            new_name='dos_style',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='droiteStyle',
            new_name='droite_style',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='faceStyle',
            new_name='face_style',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='gaucheStyle',
            new_name='gauche_style',
        ),
    ]
