# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-03 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutsomise', '0009_customiseonglet_description'),
        ('achetez', '0033_auto_20170722_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='type_produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cutsomise.customiseProduit'),
            preserve_default=False,
        ),
    ]
