# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-15 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0037_auto_20170813_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='video_confirm',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='video_mp4',
            field=models.FileField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='video_webm',
            field=models.FileField(blank=True, upload_to='achetez/produit/'),
        ),
        migrations.AlterField(
            model_name='achatlogo',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achetez.AchatCategorie'),
        ),
    ]
