# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0038_auto_20170815_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatlogo',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achetez.AchatCategorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='couleur_contour',
            field=models.CharField(default=0, max_length=7),
        ),
    ]
