# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-28 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achetez', '0039_auto_20170815_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achatlogo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logos'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Textile', 'verbose_name_plural': 'Textiles'},
        ),
        migrations.AddField(
            model_name='achatcategorie',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achatlogo',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achetez.AchatCategorie'),
        ),
    ]
