# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendre', '0003_methodedescription_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodedescription',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 7, 20, 9, 30, 53903, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
