# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customise_categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='customise/')),
                ('text_description_short', models.CharField(max_length=200)),
                ('couleur_text', models.CharField(default='black', max_length=7)),
                ('couleur_titre', models.CharField(default='white', max_length=7)),
                ('confirm', models.BooleanField()),
            ],
        ),
    ]
