# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutsomise', '0002_customise_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customise_categorie',
            name='image',
            field=models.ImageField(upload_to='customise/categorie/'),
        ),
        migrations.AlterField(
            model_name='customise_produit',
            name='image',
            field=models.ImageField(upload_to='customise/produit'),
        ),
    ]
