# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutsomise', '0003_auto_20161104_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customise_categorie',
            new_name='customiseCategorie',
        ),
        migrations.RenameModel(
            old_name='customise_produit',
            new_name='customiseProduit',
        ),
    ]
