# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutsomise', '0004_auto_20161104_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='customiseOnglet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('titre', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('image_titre', models.ImageField(upload_to='customise/titre/')),
                ('couleur_titre', models.CharField(default='white', max_length=140)),
                ('confirm', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='customiseproduit',
            name='image',
            field=models.ImageField(upload_to='customise/produit/'),
        ),
    ]
