# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutsomise', '0005_auto_20161104_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customisecategorie',
            options={'verbose_name': "Cat\xe9gorie de l'onglet Customise", 'verbose_name_plural': "Cat\xe9gories de l'onglet Customise"},
        ),
        migrations.AlterModelOptions(
            name='customiseonglet',
            options={'verbose_name': "Pr\xe9sentation de l'onglet Customise", 'verbose_name_plural': "Pr\xe9sentation de l'onglet Customise"},
        ),
        migrations.AlterModelOptions(
            name='customiseproduit',
            options={'verbose_name': "Produit de l'onglet Customise", 'verbose_name_plural': "Produits de l'onglet Customise"},
        ),
    ]
