# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutsomise', '0007_auto_20161219_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customiseonglet',
            name='image_titre',
            field=models.ImageField(upload_to='customise/image_titre/'),
        ),
    ]
