# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='particulier',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='particulier',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='professionel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='professionel',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='revendeur',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='revendeur',
            name='site_web',
            field=models.URLField(blank=True),
        ),
    ]
