# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_auto_20161222_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='utilisateur/avatars/'),
        ),
        migrations.AlterField(
            model_name='particulier',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='utilisateur/avatars/'),
        ),
        migrations.AlterField(
            model_name='professionel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='utilisateur/avatars/'),
        ),
        migrations.AlterField(
            model_name='revendeur',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='utilisateur/avatars/'),
        ),
    ]
