# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_auto_20170102_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='envoi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='particulier',
            name='envoi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionel',
            name='envoi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revendeur',
            name='envoi',
            field=models.BooleanField(default=False),
        ),
    ]
