# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_auto_20170102_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='user',
        ),
        migrations.RemoveField(
            model_name='particulier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='professionel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='revendeur',
            name='user',
        ),
        migrations.AddField(
            model_name='artiste',
            name='type_utilisateur',
            field=models.CharField(choices=[('Revendeur', 'Revendeur'), ('Particulier', 'Particulier'), ('Professionel', 'Professionel'), ('Artiste', 'Artiste')], default='Particulier', max_length=25),
        ),
        migrations.AddField(
            model_name='particulier',
            name='type_utilisateur',
            field=models.CharField(choices=[('Revendeur', 'Revendeur'), ('Particulier', 'Particulier'), ('Professionel', 'Professionel'), ('Artiste', 'Artiste')], default='Particulier', max_length=25),
        ),
        migrations.AddField(
            model_name='professionel',
            name='type_utilisateur',
            field=models.CharField(choices=[('Revendeur', 'Revendeur'), ('Particulier', 'Particulier'), ('Professionel', 'Professionel'), ('Artiste', 'Artiste')], default='Particulier', max_length=25),
        ),
        migrations.AddField(
            model_name='revendeur',
            name='type_utilisateur',
            field=models.CharField(choices=[('Revendeur', 'Revendeur'), ('Particulier', 'Particulier'), ('Professionel', 'Professionel'), ('Artiste', 'Artiste')], default='Particulier', max_length=25),
        ),
    ]
