# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-02 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateur', '0009_auto_20170102_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='type_utilisateur',
        ),
        migrations.RemoveField(
            model_name='particulier',
            name='type_utilisateur',
        ),
        migrations.RemoveField(
            model_name='professionel',
            name='type_utilisateur',
        ),
        migrations.RemoveField(
            model_name='revendeur',
            name='type_utilisateur',
        ),
        migrations.AddField(
            model_name='artiste',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='particulier',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revendeur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
