# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_Ephemere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_ephemere/')),
                ('text_description', models.TextField()),
                ('couleur_text', models.CharField(default='#111111', max_length=7)),
                ('couleur_fond', models.CharField(default='#FFFFFF', max_length=7)),
                ('contour_arrondi', models.PositiveSmallIntegerField(default=0)),
                ('contour_arrondi_image', models.PositiveSmallIntegerField(default=0)),
                ('type_contour', models.CharField(choices=[('dotted', 'dotted'), ('dashed', 'dashed'), ('solid', 'solid'), ('double', 'double'), ('groove', 'groove'), ('ridge', 'ridge'), ('inset', 'inset'), ('outset', 'outset'), ('none', 'none'), ('hidden', 'hidden')], default='none', max_length=15)),
                ('couleur_contour', models.CharField(max_length=7)),
                ('epaisseur_contour', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
