# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_ephemere', '0003_auto_20161227_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='mosaique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_ephemere/mosaique')),
                ('titre', models.CharField(max_length=140)),
                ('text_description', models.TextField()),
            ],
        ),
    ]
