# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-29 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_ephemere', '0005_mosaique_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='coloneMosaique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('confirm', models.BooleanField()),
                ('colonne_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonne_1', to='collection_ephemere.mosaique')),
                ('colonne_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colonne_2', to='collection_ephemere.mosaique')),
                ('colonne_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colonne_3', to='collection_ephemere.mosaique')),
            ],
            options={
                'verbose_name': "colonne de mosaique de l'onglet Achetez ",
                'verbose_name_plural': "colonne de mosaique de l'onglet Achetez ",
            },
        ),
    ]
