# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-29 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_ephemere', '0007_auto_20161229_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaique',
            name='colonne',
            field=models.CharField(choices=[('dotted', 'dotted'), ('dashed', 'dashed'), ('solid', 'solid'), ('double', 'double'), ('groove', 'groove'), ('ridge', 'ridge'), ('inset', 'inset'), ('outset', 'outset'), ('none', 'none'), ('hidden', 'hidden')], default='none', max_length=15),
        ),
    ]
