# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_ephemere', '0010_auto_20161229_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaique',
            name='video_mp4',
            field=models.FileField(default=1, upload_to='home/fond_ecran/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosaique',
            name='video_webm',
            field=models.FileField(blank=True, upload_to='home/fond_ecran/'),
        ),
    ]
