# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-10 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_ephemere', '0011_auto_20170310_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionephemere',
            name='pub',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosaique',
            name='video',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
