# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_ephemere', '0012_auto_20170310_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaique',
            name='video_mp4',
            field=models.FileField(upload_to='collection_ephemere/video/'),
        ),
        migrations.AlterField(
            model_name='mosaique',
            name='video_webm',
            field=models.FileField(blank=True, upload_to='collection_ephemere/video/'),
        ),
    ]
