# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_ephemere', '0014_ongletcollectionephemere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaique',
            name='video_mp4',
            field=models.FileField(blank=True, upload_to='collection_ephemere/video/'),
        ),
    ]
