# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161022_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page_accueil',
            new_name='pageAccueil',
        ),
    ]
