# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161104_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageaccueil',
            name='fondEcran',
            field=models.ImageField(upload_to='home/fond_ecran/'),
        ),
        migrations.AlterField(
            model_name='pageaccueil',
            name='logo',
            field=models.ImageField(upload_to='home/logo/'),
        ),
    ]
