# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161104_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageaccueil',
            options={'verbose_name': "Page d'accueil ", 'verbose_name_plural': "Page d'accueil "},
        ),
    ]
