# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161107_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaccueil',
            name='decalage_logo',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
