# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pageaccueil_decalage_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageaccueil',
            name='decalage_logo',
            field=models.SmallIntegerField(),
        ),
    ]
