# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161221_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaccueil',
            name='video',
            field=models.FileField(default=1, upload_to='home/fond_ecran/'),
            preserve_default=False,
        ),
    ]
