# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pageaccueil_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageaccueil',
            old_name='video',
            new_name='video_mp4',
        ),
        migrations.AddField(
            model_name='pageaccueil',
            name='video_webm',
            field=models.FileField(default=1, upload_to='home/fond_ecran/'),
            preserve_default=False,
        ),
    ]
