# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20161227_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageaccueil',
            name='video_webm',
            field=models.FileField(blank=True, upload_to='home/fond_ecran/'),
        ),
    ]
