# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20161227_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageaccueil',
            options={'verbose_name': "Page d'accueil", 'verbose_name_plural': "Page d'accueil"},
        ),
    ]
