# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-29 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20161227_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaccueil',
            name='decalage_my_custom',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageaccueil',
            name='hauteur_my_custom',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pageaccueil',
            name='decalage_logo',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
